#!/bin/bash
set -e # enable exit on error
source scripts/setup.sh

if [[
  -z "$PROJECT_NAME" ||
  -z "$PROFILE" ||
  -z "$MANIFEST_FILE_PATH" ||
  "$RPC_URL" != "http"* ||
  "$WORLD_ADDRESS" != "0x"* ||
  -z "$WORLD_BLOCK"
]]; then
  echo "! Missing data 👎"
  exit 1
fi

echo "BINDINGS_PATH: $BINDINGS_PATH"
echo "CLIENT_MANIFEST_PATH: $CLIENT_MANIFEST_PATH"

#-----------------
# build
#
echo "------------------------------------------------------------------------------"
sozo --version
echo "------------------------------------------------------------------------------"
echo ">>> Cleaning..."
execute_command "$SOZO -P $PROFILE $ARG_OFFLINE clean"
echo ">>> Building..."
execute_command "$SOZO -P $PROFILE $ARG_OFFLINE build $ARG_BINDINGS"
echo "👍"

#-----------------
# migrate
#
echo "------------------------------------------------------------------------------"
echo ">>> Inspect migrations..."
execute_command "sozo -P $PROFILE $ARG_OFFLINE inspect --world $WORLD_ADDRESS"

if [[ -n "$ARG_INSPECT" ]]; then # if is set
  echo "--- INSPECTED! 👍"
  exit 0
fi

echo ">>> Do migrations..."
# execute_command "sozo -P $PROFILE $ARG_OFFLINE migrate -vvv --world $WORLD_ADDRESS"
execute_command "sozo -P $PROFILE $ARG_OFFLINE migrate --max-calls 10 --world $WORLD_ADDRESS $ARG_VERBOSE"
echo "👍"

# echo ">>> Inspect again..."
# execute_command "sozo -P $PROFILE $ARG_OFFLINE inspect --world $WORLD_ADDRESS"

#-----------------
# auth write
#
# scripts/default_auth.sh $PROFILE

#------------------------
# copy manifest to client
#
echo "------------------------------------------------------------------------------"
echo ">>> Copying manifest [$MANIFEST_FILE_PATH] to [$CLIENT_MANIFEST_PATH/]"
mkdir -p $CLIENT_MANIFEST_PATH
cp $MANIFEST_FILE_PATH $CLIENT_MANIFEST_PATH/
echo "👍"

#
# create torii config
export GAME_TOKEN_ADDRESS=$(get_contract_address "feral-game_token")
echo "------------------------------------------------------------------------------"
echo ">>> Create torii config [$TORII_CONFIG_PATH]..."
cp $TORII_CONFIG_TEMPLATE_PATH $TORII_CONFIG_PATH
sed -i '' -e "s|\$profile|$PROFILE|g" $TORII_CONFIG_PATH
sed -i '' -e "s|\$world_address|$WORLD_ADDRESS|g" $TORII_CONFIG_PATH
sed -i '' -e "s|\$world_block|$WORLD_BLOCK|g" $TORII_CONFIG_PATH
sed -i '' -e "s|\$rpc_url|$RPC_URL|g" $TORII_CONFIG_PATH
sed -i '' -e "s|\$game_token|$GAME_TOKEN_ADDRESS|g" $TORII_CONFIG_PATH
cat $TORII_CONFIG_PATH
echo "👍"

#------------------------
# typescript bindings
#
if [[ "$PROFILE" == "dev" ]]; then
  #
  # copy typescript bindings
  if [[ -n "$ARG_BINDINGS" ]]; then # if is set
    echo ">>> Copying bindings [$BINDINGS_PATH] to [$CLIENT_MANIFEST_PATH/]"
    cp -R $BINDINGS_PATH/typescript/* $CLIENT_MANIFEST_PATH/
  fi
  #
  # list copied files
  echo "------------------------------------------------------------------------------"
  ls -ld $CLIENT_MANIFEST_PATH/* | grep -E 'ts|json'
  cd -
fi

# if [[ "$CHAIN_ID" == "SN_SEPOLIA" || "$CHAIN_ID" == "SN_MAIN" ]]; then
#   cd ../client
#   echo "------------------------------------------------------------------------------"
#   echo ">>> Generate controller preset..."
#   # npm run generate-controller-preset --sdk=../sdk/src/games/pistols
#   # npx --package=@underware/feral-sdk generate-controller-preset --chain_id:"SN_MAIN" --out:"../sdk/src/games/pistols/generated/preset.json"
#   # node --experimental-wasm-modules ../sdk/dist/bin/generateControllerPreset.mjs --chain_id:"SN_MAIN" --out:"../sdk/src/games/pistols/generated/preset.json"
#   # cd ../sdk && turbo build && cd -
#   execute_command "npm run generate-controller-preset --chain_id="$CHAIN_ID" --sdk=$CLIENT_GENERATED_PATH"
#   echo "👍?"
#   cd -
# fi

#------------------
echo "--- DONE! 👍"
