[package] 
name = "feral"
version = "0.1.2"
edition = "2024_07"
cairo-version = "2.15.0"
license = "CC0-1.0"

[cairo]
sierra-replace-ids = true
panic-backtrace = true

[dependencies]
starknet = "2.15.1"
dojo = "=1.8.0"
game_components_embeddable_game_standard = { git = "https://github.com/Provable-Games/game-components.git", tag = "v1.1.0" }
game_components_utilities = { git = "https://github.com/Provable-Games/game-components.git", tag = "v1.1.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }

[dev-dependencies]
dojo_snf_test = "=1.8.0"
assert_macros = "2.15.1"
# snforge_std = "0.51.2" # dojo_snf_test
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.55.0" }
denshokan_testing  = { git = "https://github.com/Provable-Games/denshokan.git", branch = "main" }
denshokan_token    = { git = "https://github.com/Provable-Games/denshokan.git", branch = "main" }
denshokan_registry = { git = "https://github.com/Provable-Games/denshokan.git", branch = "main" }
denshokan_renderer = { git = "https://github.com/Provable-Games/denshokan.git", branch = "main" }

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = [
  "dojo_cairo_macros",
  "snforge_scarb_plugin",
]

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = [
  "dojo::world::world_contract::world",
  "denshokan_token::denshokan::Denshokan",
  "denshokan_registry::minigame_registry::MinigameRegistry",
  "denshokan_renderer::default_renderer::DefaultRenderer",
]

# debug contract size issues
# needed by `sozo build --stats.by-tag`
# https://docs.starknet.io/resources/chain-info/
# max felts = 81,920 felts
# casm = true


#--------------------------
# Dojo profiles declaration
#
[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]
