#
# torii config for profile [dev]
#
world_address = "0x0151badfd4875c60de9a2c933c0831c8ba7acf7e29d50b4a317b6cf62fe6eccc"
rpc = "http://127.0.0.1:5050"

[events]
raw = true

[sql]
historical = [
  # "feral-TrophyProgression",
]

# [grpc]
# subscription_buffer_size = 10000

[indexing]
world_block = 1
# blocks_chunk_size = 10240 # default: 10240
# max_concurrent_tasks = 40
transactions = true
controllers = true
pending = true
contracts = [
  "erc721:0x4c9d641499b4f670b434f3089340546d8910a926b969652bb7d58f5a692f774", # game_token
]
