#
# torii config for profile [mainnet]
#
world_address = "0x0151badfd4875c60de9a2c933c0831c8ba7acf7e29d50b4a317b6cf62fe6eccc"
rpc = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_9"

[events]
raw = true

[sql]
historical = [
  # "feral-TrophyProgression",
]

# [grpc]
# subscription_buffer_size = 10000

[indexing]
world_block = 88597
# blocks_chunk_size = 10240 # default: 10240
# max_concurrent_tasks = 40
transactions = true
controllers = true
pending = true
contracts = [
  "erc721:0x063dfbb323632b55ab714d4315775cc2e56f6bfdce49230aad9b2490763c0958", # game_token
]
